###
GET http://localhost:5000/api/goals/61de32d668d67d0b669ba1ba
Content-Type: application/json

###
GET http://localhost:5000/api/goals/details/61de3684f0f58ce7146ce147
Content-Type: application/json


###
POST http://localhost:5000/api/goals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZGVlNTY1NGNiN2I1OTNiYWFiZWEiLCJpYXQiOjE2MzcwNTcxODl9.x7vmhYAlAEXUCxJ4u04nDMsocOE4LE6RmO7_QWe8u7Y

{
    "schedulerId": "61de32d668d67d0b669ba1ba",
    "teamId": "61dc3367769aa631accf9d8b",
    "playerId": "61dda10feb9b4716a4e09530",
    "videoId": "Vd9j1t_SqZs",
    "atTime": "80"
}